# permissions for end users to edit credentialrotators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialrotator-editor-role
rules:
- apiGroups:
  - security.example.com
  resources:
  - credentialrotators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.example.com
  resources:
  - credentialrotators/status
  verbs:
  - get
