# permissions for end users to view credentialrotators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialrotator-viewer-role
rules:
- apiGroups:
  - security.example.com
  resources:
  - credentialrotators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.example.com
  resources:
  - credentialrotators/status
  verbs:
  - get
